[basics]
name = "Jean Carlos Tomichá Ressa"
label = "Ingeniero Electromecánico"
image = ""
email = "jeancarlos.ingenieria@gmail.com"
phone = ""
url = "https://jeancarlos.dev"
summary = "+5 años de experiencia"

  [basics.location]
  city = "Santa Cruz"
  countryCode = "80"
  region = "Santa Cruz"

  [[basics.profiles]]
  network = "LinkedIn"
  username = "jeancarlos"
  url = "https://linkedin.com"

  [[basics.profiles]]
  network = "GitHub"
  username = "jeancarlos"
  url = "https://github.com"

[[work]]
name = "Villavicencio"
position = "Ingeniero"
location = "Santa Cruz, Bolivia"
startDate = "2022-03"
endDate = ""
summary = ""
highlights = [ "Coordinación técnico" ]

[[education]]
institution = "Universidad"
location = "Santa Cruz, Bolivia"
area = "Ing. electromecanica"
studyType = "Licenciatura"
endDate = "2022"

[[skills]]
name = "Diseño eléctrico"

[[languages]]
language = "Español"

[[Certificates]]
name = ""
issuer = ""
date = ""

